import { makeStyles } from "@mui/styles";
import { COLORS } from "~/assets/colors/colors";

const useStyles = makeStyles({
  reportDetailContainer: {
    maxWidth: "1320px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
  },
  detailTable: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: "0px",
    backgroundColor: COLORS.COLOR.WHITE,
    border: `1px solid ${COLORS.STORKE.CONTENTS2}`,
    borderRadius: "8px",
    boxShadow: "0 4px 22px 0 rgba(0, 0, 0, 0.05)",
  },
  detailContentStyle: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: "64px",
    display: "flex",
    alignItems: "center",
  },
  titleLayout: {
    boxSizing: "border-box",
    width: "100%",
    maxWidth: "250px",
    height: "100%",
    display: "flex",
    alignItems: "center",
    paddingLeft: "30px",
    wordBreak: "keep-all",
    fontSize: "14px",
    lineHeight: "150%",
    color: "#272833",
  },
  detailContent: {
    boxSizing: "border-box",
    display: "flex",
    alignContent: "center",
    fontSize: "14px",
    lineHeight: "150%",
    padding: "20px 30px",
    width: "100%",
    color: "#272833 ",
    wordBreak: "break-all",
    borderLeft: `1px solid ${COLORS.STORKE.CONTENTS2}`,
  },
  submitBtn: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginTop: "50px",
    flexDirection: "row",
    columnGap: "30px",
  },
  backBtn: {
    boxSizing: "border-box",
    backgroundColor: "transparent",
    fontSize: "14px",
    cursor: "pointer",
    color: COLORS.COLOR.BLACK,
    borderRadius: "8px",
    width: "120px",
    height: "36px",
    wordBreak: "keep-all",
    border: `1px solid ${COLORS.COLOR.BLACK}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
});
export default useStyles;
